# app/services/agent_webservice/state.py
from typing import TypedDict

class AgentState(TypedDict):
    """
    Defines the structure of the data shared between nodes in the LangGraph.
    """
    input: str     # The original message sent by the user
    response: str  # The final text generated by the agent
    route: str     # The classified intent (e.g., 'purchase', 'delivery', 'rate')